server: # REST server
  port: 2333
  address: localhost
lavalink:
  server:
    password: "b1nzyR8l1m1t5"
    ws:
      port: 80
      host: localhost
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: true
    sentryDsn: ""
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 600